# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e71e660e091db9f2f1eec47f0403a473bfdcb36c7b64a288ca967b3eaf0fcf421fc40b947160f240a9a1468edd7e44e0e011283e011273709c7e1f664c0008fa

test:
  secret_key_base: 6d579173aa4f41335a3391831b6502f598fa98aa4db67a24c6d92b3bd2aadd735d690a332d8ec54d4a689801f1c7ab42299d03165468a0ff866a409f78a5a706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
